$op: pipe
do:
  - title:
      $op: doc.get
      key: title
    url:
      $op: doc.get
      key:
        - location
        - href
    text:
      $op: html.markdown
      html:
        $op: html.simplify
        html:
          $op: doc.get
          key:
            - documentElement
            - outerHTML
  - $op: fs.saveFile
    filename:
      $op: str.join
      values:
        - $op: get
          key: title
        - ".md"
    content:
      $op: template.render
      template: |
        ---
        title: {{title}}
        url: {{url}}
        ---

        {{text}}
