$op: pipe
do:
  - title:
      $op: doc.get
      key: title
    url:
      $op: doc.get
      key:
        - location
        - href
    hostname:
      $op: doc.get
      key:
        - location
        - hostname
    selection:
      $op: doc.selection
  - $op: ctx.update
    properties:
      text:
        $op: html.markdown
        html:
          $op: html.simplify
          baseUrl:
            $op: ctx.get
            key: url
          html:
            $op: doc.get
            key:
              - documentElement
              - outerHTML
  - $op: fs.saveFile
    filename:
      $op: str.join
      values:
        - $op: ctx.get
          key: title
        - ".md"
    content:
      $op: template.render
      template: |
        ---
        page-title: {{{json title}}}
        url: {{url}}
        hostname: {{hostname}}
        reviewed: false
        ---

        {{#if selection}}
        {{quote selection}}

        {{/if}}
        {{text}}
